### ISSUE TITLE
trainer이슈

### ISSUE THREAD

**Issue by Mysigyeong** [2019-iuc-sw-skku/ssenstone#55]
1. 오토인코더 1회성 문제
2. Show Result누르고 confusion matrix뜰때까지 GUI가 멈추는 현상
3. 학습 중간에 창을 닫으면 창만 닫히고 학습은 계속 하는 현상(중간에 끊기게 하는 것이 좋지 않을까)

**Comment by Jiwon-Park** [comment]
#56 
1번 고침
